import type { PlaybookTemplate } from '../types';

export const BUILTIN_PLAYBOOKS: PlaybookTemplate[] = [
  {
    id: 'pb-incident-response',
    name: 'Incident Response (Generic)',
    description: 'Standard IR workflow: detect, contain, eradicate, recover, and review.',
    icon: '\uD83D\uDEA8',
    investigationType: 'incident-response',
    defaultTags: ['incident-response'],
    defaultClsLevel: 'TLP:AMBER',
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'note', title: 'IR Triage Checklist', content: '', noteTemplateId: 'bt-ir-triage', phase: 'Detection', tags: ['triage'] },
      { order: 2, entityType: 'task', title: 'Confirm incident and rule out false positive', content: 'Validate alerting data, correlate with additional sources, and confirm the incident is real.', priority: 'high', status: 'todo', phase: 'Detection', tags: ['triage'] },
      { order: 3, entityType: 'task', title: 'Determine scope and affected assets', content: 'Identify all affected systems, users, and data. Document the blast radius.', priority: 'high', status: 'todo', phase: 'Detection', tags: ['scoping'] },
      { order: 4, entityType: 'task', title: 'Collect and document initial IOCs', content: 'Extract IPs, domains, hashes, email addresses, and other indicators from available evidence.', priority: 'high', status: 'todo', phase: 'Detection', tags: ['ioc-collection'] },
      { order: 5, entityType: 'task', title: 'Isolate affected systems', content: 'Network isolation, disable accounts, block IPs/domains as appropriate.', priority: 'high', status: 'todo', phase: 'Containment', tags: ['containment'] },
      { order: 6, entityType: 'task', title: 'Preserve forensic evidence', content: 'Memory dumps, disk images, log exports. Maintain chain of custody.', priority: 'medium', status: 'todo', phase: 'Containment', tags: ['forensics'] },
      { order: 7, entityType: 'task', title: 'Eradicate threat from environment', content: 'Remove malware, patch vulnerabilities, close unauthorized access paths.', priority: 'high', status: 'todo', phase: 'Eradication', tags: ['eradication'] },
      { order: 8, entityType: 'task', title: 'Restore affected systems to normal operation', content: 'Rebuild/restore from clean backups, verify integrity, monitor for reinfection.', priority: 'medium', status: 'todo', phase: 'Recovery', tags: ['recovery'] },
      { order: 9, entityType: 'task', title: 'Conduct post-incident review', content: 'Lessons learned, root cause analysis, update detection rules and playbooks.', priority: 'medium', status: 'todo', phase: 'Lessons Learned', tags: ['review'] },
      { order: 10, entityType: 'note', title: 'Post-Incident Review', content: '', noteTemplateId: 'bt-post-incident', phase: 'Lessons Learned', tags: ['review'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'pb-phishing',
    name: 'Phishing Investigation',
    description: 'Investigate a phishing campaign: analyze emails, check infrastructure, contain exposure.',
    icon: '\uD83C\uDFA3',
    investigationType: 'phishing',
    defaultTags: ['phishing'],
    defaultClsLevel: 'TLP:AMBER',
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'note', title: 'Phishing Campaign Report', content: '', noteTemplateId: 'bt-phishing-report', phase: 'Analysis', tags: ['phishing'] },
      { order: 2, entityType: 'task', title: 'Analyze email headers and sender reputation', content: 'Check SPF, DKIM, DMARC. Trace sending infrastructure. Check sender against known-bad lists.', priority: 'high', status: 'todo', phase: 'Analysis', tags: ['email-analysis'] },
      { order: 3, entityType: 'task', title: 'Analyze URLs and attachments', content: 'Detonate in sandbox, check VirusTotal, URLhaus. Document payload behavior.', priority: 'high', status: 'todo', phase: 'Analysis', tags: ['payload-analysis'] },
      { order: 4, entityType: 'task', title: 'Extract and document IOCs', content: 'Sender IPs, domains, URLs, file hashes. Add to IOC tracker.', priority: 'high', status: 'todo', phase: 'Analysis', tags: ['ioc-collection'] },
      { order: 5, entityType: 'task', title: 'Determine scope of exposure', content: 'How many users received the email? Who clicked? Who submitted credentials?', priority: 'high', status: 'todo', phase: 'Scoping', tags: ['scoping'] },
      { order: 6, entityType: 'task', title: 'Block malicious infrastructure', content: 'Block sender domain, payload URLs, and C2 domains at email gateway and firewall.', priority: 'high', status: 'todo', phase: 'Containment', tags: ['containment'] },
      { order: 7, entityType: 'task', title: 'Reset compromised credentials', content: 'Force password reset for any users who submitted credentials. Revoke active sessions.', priority: 'high', status: 'todo', phase: 'Containment', tags: ['containment'] },
      { order: 8, entityType: 'task', title: 'Notify affected users', content: 'Send awareness communication. Provide guidance on what to watch for.', priority: 'medium', status: 'todo', phase: 'Recovery', tags: ['communication'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'pb-malware',
    name: 'Malware Analysis',
    description: 'Analyze a malware sample: static analysis, dynamic analysis, IOC extraction, detection rules.',
    icon: '\uD83E\uDDA0',
    investigationType: 'malware-analysis',
    defaultTags: ['malware'],
    defaultClsLevel: 'TLP:AMBER',
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'note', title: 'Malware Sample Analysis', content: '', noteTemplateId: 'bt-malware-sample', phase: 'Analysis', tags: ['malware'] },
      { order: 2, entityType: 'task', title: 'Perform static analysis', content: 'File type, strings, imports, PE headers, packer detection. Document findings.', priority: 'high', status: 'todo', phase: 'Static Analysis', tags: ['static-analysis'] },
      { order: 3, entityType: 'task', title: 'Perform dynamic analysis', content: 'Execute in sandbox. Monitor process behavior, file system changes, registry modifications, network traffic.', priority: 'high', status: 'todo', phase: 'Dynamic Analysis', tags: ['dynamic-analysis'] },
      { order: 4, entityType: 'task', title: 'Analyze network behavior and C2', content: 'Identify C2 servers, communication protocols, beacon intervals, data exfiltration methods.', priority: 'high', status: 'todo', phase: 'Network Analysis', tags: ['network-analysis'] },
      { order: 5, entityType: 'task', title: 'Document persistence mechanisms', content: 'Registry keys, scheduled tasks, services, startup folders, DLL hijacking, etc.', priority: 'medium', status: 'todo', phase: 'Analysis', tags: ['persistence'] },
      { order: 6, entityType: 'task', title: 'Extract and catalog IOCs', content: 'Hashes, IPs, domains, URLs, mutexes, file paths, registry keys.', priority: 'high', status: 'todo', phase: 'IOC Extraction', tags: ['ioc-collection'] },
      { order: 7, entityType: 'task', title: 'Write YARA detection rule', content: 'Create YARA rule based on unique strings, byte patterns, or structural characteristics.', priority: 'medium', status: 'todo', phase: 'Detection', tags: ['yara'] },
      { order: 8, entityType: 'task', title: 'Write final analysis report', content: 'Summarize findings, IOCs, MITRE ATT&CK mapping, and detection recommendations.', priority: 'medium', status: 'todo', phase: 'Reporting', tags: ['reporting'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'pb-threat-hunt',
    name: 'Threat Hunt',
    description: 'Hypothesis-driven threat hunting: form hypothesis, query data, analyze results.',
    icon: '\uD83D\uDD2D',
    investigationType: 'threat-hunt',
    defaultTags: ['threat-hunt'],
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'note', title: 'Hunt Hypothesis', content: '', noteTemplateId: 'bt-hunt-hypothesis', phase: 'Planning', tags: ['hypothesis'] },
      { order: 2, entityType: 'task', title: 'Define hypothesis and MITRE mapping', content: 'Document the specific threat behavior being hunted and map to ATT&CK techniques.', priority: 'high', status: 'todo', phase: 'Planning', tags: ['planning'] },
      { order: 3, entityType: 'task', title: 'Identify required data sources', content: 'Determine which logs, telemetry, and data sources are needed. Verify coverage and retention.', priority: 'high', status: 'todo', phase: 'Planning', tags: ['data-sources'] },
      { order: 4, entityType: 'task', title: 'Develop hunt queries', content: 'Write queries/analytics for the target data sources. Test against known-good baselines.', priority: 'high', status: 'todo', phase: 'Execution', tags: ['queries'] },
      { order: 5, entityType: 'task', title: 'Execute hunt and collect results', content: 'Run queries across the environment. Triage and prioritize findings.', priority: 'high', status: 'todo', phase: 'Execution', tags: ['execution'] },
      { order: 6, entityType: 'task', title: 'Analyze results and investigate leads', content: 'Deep-dive into suspicious findings. Correlate with threat intelligence.', priority: 'high', status: 'todo', phase: 'Analysis', tags: ['analysis'] },
      { order: 7, entityType: 'task', title: 'Document findings and recommendations', content: 'Record confirmed findings, false positives, detection gaps, and recommended mitigations.', priority: 'medium', status: 'todo', phase: 'Reporting', tags: ['reporting'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'pb-data-breach',
    name: 'Data Breach Investigation',
    description: 'Investigate a potential data breach: scope, classify, contain, notify.',
    icon: '\uD83D\uDD13',
    investigationType: 'data-breach',
    defaultTags: ['data-breach'],
    defaultClsLevel: 'TLP:RED',
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'task', title: 'Assess scope of data exposure', content: 'Identify what data was accessed/exfiltrated, volume, and sensitivity level.', priority: 'high', status: 'todo', phase: 'Assessment', tags: ['scoping'] },
      { order: 2, entityType: 'task', title: 'Classify affected data', content: 'PII, PHI, financial data, credentials, intellectual property, etc. Determine regulatory implications.', priority: 'high', status: 'todo', phase: 'Assessment', tags: ['classification'] },
      { order: 3, entityType: 'task', title: 'Preserve evidence and maintain chain of custody', content: 'Log exports, memory dumps, disk images. Document all evidence handling.', priority: 'high', status: 'todo', phase: 'Evidence', tags: ['forensics'] },
      { order: 4, entityType: 'task', title: 'Determine attack vector and timeline', content: 'How did the attacker gain access? When did the breach start/end?', priority: 'high', status: 'todo', phase: 'Analysis', tags: ['analysis'] },
      { order: 5, entityType: 'task', title: 'Contain the breach', content: 'Close access paths, revoke compromised credentials, patch exploited vulnerabilities.', priority: 'high', status: 'todo', phase: 'Containment', tags: ['containment'] },
      { order: 6, entityType: 'task', title: 'Assess notification requirements', content: 'GDPR, HIPAA, state breach notification laws, contractual obligations.', priority: 'high', status: 'todo', phase: 'Legal', tags: ['legal'] },
      { order: 7, entityType: 'task', title: 'Draft notification communications', content: 'Affected individuals, regulators, business partners as required.', priority: 'medium', status: 'todo', phase: 'Communication', tags: ['communication'] },
      { order: 8, entityType: 'task', title: 'Implement remediation measures', content: 'Address root cause, strengthen controls, update monitoring.', priority: 'medium', status: 'todo', phase: 'Remediation', tags: ['remediation'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'pb-vuln-assessment',
    name: 'Vulnerability Assessment',
    description: 'Assess and remediate a critical vulnerability across the environment.',
    icon: '\uD83D\uDEE1\uFE0F',
    investigationType: 'vulnerability',
    defaultTags: ['vulnerability'],
    source: 'builtin',
    steps: [
      { order: 1, entityType: 'note', title: 'Vulnerability Assessment', content: '', noteTemplateId: 'bt-vuln-assessment', phase: 'Discovery', tags: ['vulnerability'] },
      { order: 2, entityType: 'task', title: 'Identify all affected systems', content: 'Scan environment, check asset inventory, determine full exposure.', priority: 'high', status: 'todo', phase: 'Discovery', tags: ['scanning'] },
      { order: 3, entityType: 'task', title: 'Validate exploitability', content: 'Confirm if the vulnerability is exploitable in your environment. Check for mitigating controls.', priority: 'high', status: 'todo', phase: 'Validation', tags: ['validation'] },
      { order: 4, entityType: 'task', title: 'Assess business impact', content: 'Determine impact on confidentiality, integrity, and availability. Map to business processes.', priority: 'high', status: 'todo', phase: 'Assessment', tags: ['impact'] },
      { order: 5, entityType: 'task', title: 'Develop and test remediation plan', content: 'Identify patch or workaround. Test in staging environment.', priority: 'high', status: 'todo', phase: 'Remediation', tags: ['patching'] },
      { order: 6, entityType: 'task', title: 'Deploy remediation to production', content: 'Roll out patch/fix with change management. Monitor for issues.', priority: 'high', status: 'todo', phase: 'Remediation', tags: ['deployment'] },
      { order: 7, entityType: 'task', title: 'Verify remediation', content: 'Re-scan to confirm vulnerability is resolved. Update vulnerability tracker.', priority: 'medium', status: 'todo', phase: 'Verification', tags: ['verification'] },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
];

export const BUILTIN_INVESTIGATION_TYPES = [
  'incident-response',
  'phishing',
  'malware-analysis',
  'threat-hunt',
  'data-breach',
  'vulnerability',
  'custom',
] as const;
